[project]
name = "news-summarizer"
version = "0.1.0"
description = "Collecting various industry news from designated information sources by AI, â€œnews-summarizerâ€ summarizes key points and sends them to you"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
